# Generated by Django 3.0.3 on 2020-02-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200, verbose_name='Nama Penuh')),
                ('ic_text', models.CharField(max_length=14, verbose_name='Kad Pengenalan')),
                ('sex', models.BooleanField(verbose_name='Jantina')),
                ('monthly_salary_text', models.IntegerField(verbose_name='Pendapatan Sebulan')),
            ],
        ),
    ]
